baseURL = 'https://cohub-hugo.netlify.app'
# languageCode = 'en-us'
languageName = "Français"
languageCode = "fr-fr"
defaultContentLanguage = "fr"
paginate = 6
themes= "coHub"
disableLanguages = ["en"]
title = 'lcDigitale - Agence Web 360°- Site Internet '
 
[Menu]
  # Main Menu
  [[Languages.fr.menu.main]]
  name = "Pour qui ?"
  url= "#gallery"
  weight = 1
  [[Languages.fr.menu.main]]
  name = "Nos services"
  url= "#service"
  weight = 1
  [[Languages.fr.menu.main]]
  name = "Nos valeurs"
  url= "/about/"
  weight = 3
  [[Languages.fr.menu.main]]
  name = "Témoignages"
  url= "#blog"
  weight = 4
  [[Languages.fr.menu.main]]
  name = "Tarifs"
  url= "#pricing"
  weight = 5
  [[Languages.fr.menu.main]]
  name = "FAQ"
  url= "#faq"
  weight = 6
  [[Languages.fr.menu.main]]
  name = "Contact"
  url= "/contact/"
  weight = 7

  # Sitemap Menu
  [[menu.sitemap]]
  name = "Privacy Policy"
  url = "/privacy/"
  weight = 1
  [[menu.sitemap]]
  name = "Terms"
  url = "/terms/"
  weight = 2

[params]
  aboutPageURL = "blog"
  contactLink = "contact"
  copyright = "© {year} <a href=\"https://staticmania.com/\" target=\"_blank\">StaticMania </a>"
  fabFormURL =  "https://fabform.io/f/u00kv3-"
  googleAnalytics = "G-JZ95FEWF9K"
  logo = "images/lc.png"
  footerlogo = "images/lc.png"
  footerDescription = "Agence web 365° création de site internet sur mesure, communication, publicité, graphisme."

  [params.address]
  address = "44 Av. Alsace Loraine, <br>  Toulouse, 31000"
  email = "contact@lcdigitale.fr"
  openingDesc = "Appelez-nous ou passez nous voir à tout moment. Nous nous efforçons de répondre à toutes les demandes dans les 24 heures les jours ouvrables."
  openingHours = "Nous sommes ouverts de 7h à 19h en semaine."
  phone = "05 32 66 97 91"

  [params.map]
  APIkey = "AIzaSyC9rV6yesIygoVKTD6QLf_iCa9eiIIHqZ0"
  latitude = "45.4502528"
  longitude = "-122.783407"
  pinImage = "images/pin.png"

  # Socail icons
  [[params.social]]
  icon = "ti-facebook"
  url = "https://www.facebook.com/"
  weight = 1
  [[params.social]]
  icon = "ti-twitter-alt"
  url = "https://twitter.com/"
  weight = 2
  [[params.social]]
  icon = "ti-dribbble"
  url = "https://dribbble.com/"
  weight = 3
  [[params.social]]
  icon = "ti-instagram"
  url = "https://www.instagram.com/"
  weight = 4
  
  
